# Generated by Django 2.2.15 on 2020-08-16 22:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificated', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Imagen de perfil')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificated', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('reference_image', models.ImageField(upload_to='categoria/', verbose_name='Imagen de referencia')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificated', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('subject', models.CharField(max_length=100, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificated', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificated', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificated', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('us', models.TextField(verbose_name='Nosotros')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificated', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Título del Post')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug')),
                ('reading', models.IntegerField(default=10, verbose_name='Tiempo de lectura (nº entero)')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('body1', ckeditor.fields.RichTextField()),
                ('reference_image1', models.ImageField(max_length=255, upload_to='imagenes/', verbose_name='Imagen Referencial 1')),
                ('body2', ckeditor.fields.RichTextField(null=True)),
                ('reference_image2', models.ImageField(max_length=255, null=True, upload_to='imagenes/', verbose_name='Imagen Referencial 2')),
                ('body3', ckeditor.fields.RichTextField(null=True)),
                ('reference_image3', models.ImageField(max_length=255, null=True, upload_to='imagenes/', verbose_name='Imagen Referencial 2')),
                ('quoted', models.CharField(max_length=250, null=True, verbose_name='Introduce cita literal')),
                ('publish', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('publicated', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('featured', models.CharField(choices=[('normal', 'Normal'), ('featured', 'Featured')], default='normal', max_length=15)),
                ('promoted', models.CharField(choices=[('normal', 'Normal'), ('promoted', 'Promoted')], default='normal', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
