# Generated by Django 2.2.15 on 2020-08-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('normal', 'Normal'), ('featured', 'Featured')], default='normal', max_length=15, verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='promoted',
            field=models.CharField(choices=[('normal', 'Normal'), ('promoted', 'Promoted')], default='normal', max_length=15, verbose_name='Promocionado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicated',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_image3',
            field=models.ImageField(max_length=255, null=True, upload_to='imagenes/', verbose_name='Imagen Referencial 3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='redessociales',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='web',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('desactivated', 'Desactivated')], default='activated', max_length=15, verbose_name='Estado'),
        ),
    ]
