# Generated by Django 2.2.15 on 2020-08-18 16:12

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200816_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='post',
            name='promoted',
        ),
        migrations.AlterField(
            model_name='post',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body3',
            field=ckeditor.fields.RichTextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='quoted',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Introduce cita literal'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_image2',
            field=models.ImageField(blank=True, max_length=255, upload_to='imagenes/', verbose_name='Imagen Referencial 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_image3',
            field=models.ImageField(blank=True, max_length=255, upload_to='imagenes/', verbose_name='Imagen Referencial 3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=150, unique_for_date='publish', verbose_name='Slug'),
        ),
    ]
